db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Alberta"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Alaska"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Alabama"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Arkansas"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"American Samoa"});
db.territoryCOUNT.save({"territory":"Southwest","territoryID":"4","state":"Arizona"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"British Columbia"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Bayern"});
db.territoryCOUNT.save({"territory":"Southwest","territoryID":"4","state":"California"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Colorado"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Connecticut"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"District of Columbia"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Delaware"});
db.territoryCOUNT.save({"territory":"United Kingdom","territoryID":"10","state":"England"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Florida"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Micronesia"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Georgia"});
db.territoryCOUNT.save({"territory":"Southwest","territoryID":"4","state":"Guam"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Hessen"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Hamburg"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Hawaii"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Iowa"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Idaho"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Illinois"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Indiana"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Kansas"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Kentucky"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Louisiana"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Labrador"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Massachusetts"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Manitoba"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Maryland"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Maine"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Marshall Islands"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Michigan"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Minnesota"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Missouri"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Northern Mariana Islands"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Mississippi"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Montana"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Brunswick"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"North Carolina"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"North Dakota"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Nebraska"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Newfoundland"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"New Hampshire"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"New Jersey"});
db.territoryCOUNT.save({"territory":"Southwest","territoryID":"4","state":"New Mexico"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Nova Scotia"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"New South Wales"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Northwest Territories"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Nevada"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Nordrhein-Westfalen"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"New York"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Ohio"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Oklahoma"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Ontario"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Oregon"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Pennsylvania"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Prince Edward Island"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Puerto Rico"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Palau"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Quebec"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Queensland"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Rhode Island"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"South Australia"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"South Carolina"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"South Dakota"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Saskatchewan"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Saarland"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Tasmania"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Tennessee"});
db.territoryCOUNT.save({"territory":"Southwest","territoryID":"4","state":"Texas"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Utah"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Virginia"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"Virgin Islands"});
db.territoryCOUNT.save({"territory":"Australia","territoryID":"9","state":"Victoria"});
db.territoryCOUNT.save({"territory":"Northeast","territoryID":"2","state":"Vermont"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Washington"});
db.territoryCOUNT.save({"territory":"Central","territoryID":"3","state":"Wisconsin"});
db.territoryCOUNT.save({"territory":"Southeast","territoryID":"5","state":"West Virginia"});
db.territoryCOUNT.save({"territory":"Northwest","territoryID":"1","state":"Wyoming"});
db.territoryCOUNT.save({"territory":"Canada","territoryID":"6","state":"Yukon Territory"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"France"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Brandenburg"});
db.territoryCOUNT.save({"territory":"Germany","territoryID":"8","state":"Saxony"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Ain"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Aisne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Allier"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Alpes-de-Haute Provence"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Alpes (Haute)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Alpes-Maritimes"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Ardèche"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Ardennes"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Ariège"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Aube"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Aude"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Aveyron"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Bouches du Rhône"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Calvados"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Cantal"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Charente"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Charente-Maritime"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Cher"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Corrèze"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Corse"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Côte d'Or"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Côtes-d'Armor"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Creuse"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Dordogne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Toubs"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Drôme"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Eure"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Eure et Loir"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Finistère"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Gard"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Garonne (Haute)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Gers"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Gironde"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Hérault"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Ille et Vilaine"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Indre"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Indre et Loire"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Isère"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Jura"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Landes"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Loir et Cher"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Loire"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Loire (Haute)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Loire Atlantique"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Loiret"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Lot"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Lot et Garonne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Lozère"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Maine et Loire"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Manche"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Marne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Marne (Haute)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Mayenne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Meurthe et Moselle"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Meuse"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Morbihan"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Moselle"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Nièvre"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Nord"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Oise"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Orne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Pas de Calais"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Puy de Dôme"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Pyrénées Atlantiques"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Pyrénées (Hautes)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Pyrénées Orientales"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Rhin (Bas)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Rhin (Haut)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Rhône"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Saône (Haute)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Saône et Loire"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Sarthe"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Savoie"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Savoie Haute"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Seine (Paris)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Seine Maritime"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Seine et Marne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Yveline"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Sèvres (Deux)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Somme"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Tarne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Tarne et Garonne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Var"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Vaucluse"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"La Vendée"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Vienne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Vienne (Haute)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Vosges"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Yonne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Belford (Territoire de)"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Essonne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Hauts de Seine"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Seine Saint Denis"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Val de Marne"});
db.territoryCOUNT.save({"territory":"France","territoryID":"7","state":"Val d'Oise"});
